name: Deploy to Server

on:
  push:
    branches: ["development"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print Environment Variables
      run: |
        echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@172.30.1.2 'bash -s' < ./deploy-script.sh
